# Generated by Django 5.0.2 on 2024-02-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='WatchList',
        ),
    ]
