# Generated by Django 5.0.2 on 2024-02-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_rename_movies_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplatform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
