# Generated by Django 5.0.2 on 2024-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_watchlist_created_watchlist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
